version: '3'
services:
  symfony:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: basic
    volumes:
      - ./app:/var/www/html
    ports:
      - 8000:8000
    networks:
      - symfony
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sf5_db
      MYSQL_ROOT_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080   
networks:
  symfony: